spring:
    application:
        name: livre-service
    datasource:
        url: jdbc:mysql://localhost:3306/livresdb
        username: root
        password: Abdelkader1919
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update

server:
    port: 8088

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
