spring:
    application:
        name: livre-service
    datasource:
        url: jdbc:mysql://localhost:3306/livresdb
        username: root
        password: Abdelkader1919
    jpa:
        hibernate:
            ddl-auto: update
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka

server:
    port: 8088