spring:
  datasource:
    url: jdbc:mysql://localhost:3306/categoriesdb  # L'URL de votre base de données
    username: root  # Votre utilisateur MySQL
    password: Abdelkader1919  # Votre mot de passe MySQL


  jpa:
    hibernate:
      ddl-auto: update  # Permet à Hibernate de créer ou mettre à jour les tables automatiquement

    show-sql: true  # Affiche les requêtes SQL exécutées dans la console (utile pour le débogage)
