server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: livre-service
          uri: lb://livre-service
          predicates:
            - Path=/api/livres/**
        - id: commande-service
          uri: lb://commande-service
          predicates:
            - Path=/api/commandes/**
        - id: livre-service-categorie
          uri: lb://livre-service
          predicates:
            - Path=/api/categories/**
        - id: auth-api-user
          uri: lb://auth-api
          predicates:
            - Path=/api/users/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
