spring:
  application:
    name: commande-service
  datasource:
    url: jdbc:mysql://localhost:3306/commandesdb  # Correction ici
    username: root
    password: Abdelkader1919
  jpa:
    hibernate:
      ddl-auto: update
    show:-sql: true # affiche les requettes dans le console
    properties:
      hibernate:
        format_sql: true # formatte les reqeuttes sql pour le rendre lisibles

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE





eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka


server:
  port: 8089
