spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Abdelkader1919
  ## Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update   # Utilisez 'update' uniquement en développement
    open-in-view: false

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000  # 1h in milliseconds
server:
  port: 8005
