server:
  port: 8080
spring:
  applications:
    name: api_gateway_service
cloud:
  gateway:
    routes:
      - id : livre-service
        uri: lb://livre-service
        predicates:
         - path:api/livres/**
         -  id : commande-service
            uri: lb://commande-service
            predicates:
              - path:api/commandes/**
  eureka:
    client:
      service-url:
        defaultzone : http//localhost:8761/eureka